global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: "exemplar-demo"
    static_configs:
      - targets: ["app:8080"]
storage:
  exemplars:
    max_exemplars: 100000
